# @package _global_

offline: true # set wandb logger in offline mode for dev tests

# -----------------------------------------------------------------------------
# Code & neural decoder
# -----------------------------------------------------------------------------

code:
  _target_: sbnd.codes.LinearCode
  mat_file: ${codes_dir}/bch.31.21.mat

decoder:
  _target_: sbnd.mocked.MockedDecoder
  error_space: ${error_space}

# -----------------------------------------------------------------------------
# Datasets for training, validation and testing
# -----------------------------------------------------------------------------
# 512K = 524288, 1M = 1048576, 2M = 2097152, 4M = 4194304, 16M = 16777216

data:  
  _target_: sbnd.data.SBNDDataModule
  ebno_dB_train: 3.0
  on_demand: true
  n_train_samples: 1048576
  train_bs: 4096
  n_val_samples: 524288
  val_bs: 4096
  ebno_dB_test: [2.0, 3.0, 4.0]
  n_test_samples: 2097152
  test_bs: 4096
  error_space: ${error_space}

# -----------------------------------------------------------------------------
# Model-specific training setup
# -----------------------------------------------------------------------------

max_epochs: 16
lr: 0.005

optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: ${lr}
  weight_decay: 0.01

lr_scheduler: 
  _partial_: true
  _target_: sbnd.lr_sched.WarmupStableDecayLR
  total: ${max_epochs}
  warmup: 8
  decay: 0

# -----------------------------------------------------------------------------
# Lightning module
# -----------------------------------------------------------------------------

model:
  _target_: sbnd.model.SBNDLitModule
  decoder:  ${decoder}
  optimizer: ${optimizer}
  lr_scheduler: ${lr_scheduler} 
