# @package _global_

# -----------------------------------------------------------------------------
# Code & neural decoder
# -----------------------------------------------------------------------------

code:
  _target_: sbnd.codes.LinearCode
  mat_file: ${codes_dir}/bch.31.21.mat

decoder:
  _target_: sbnd.gru.StackedGRU
  hidden_sz: 256
  n_layers: 2
  n_steps: 10
  dropout: 0.2

# -----------------------------------------------------------------------------
# Datasets for training, validation and testing
# -----------------------------------------------------------------------------
# 512K = 524288, 1M = 1048576, 2M = 2097152, 4M = 4194304, 16M = 16777216, 1B = 1073741824

data:  
  _target_: sbnd.data.SBNDDataModule
  ebno_dB_train: 3.0
  on_demand: false
  train_file: ${data_dir}/bch-31-21/train-ml-4M-3dB.mat
  n_train_samples: 1048576  # train on the first 1M samples only
  train_bs: 4096
  val_file: ${data_dir}/bch-31-21/val-ml-512K-3dB.mat
  val_bs: 4096
  ebno_dB_test: [2.0, 3.0, 4.0]
  n_test_samples: 2097152
  test_bs: 4096
  transform:
    _partial_: true
    _target_: sbnd.transforms.BCHPerms

# -----------------------------------------------------------------------------
# Model-specific training setup
# -----------------------------------------------------------------------------

max_epochs: 512
lr: 0.005

optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: ${lr}
  weight_decay: 0.02

lr_scheduler: 
  _partial_: true
  _target_: sbnd.lr_sched.WarmupStableDecayLR
  total: ${max_epochs}
  warmup: 10
  decay: 32

# -----------------------------------------------------------------------------
# Lightning module
# -----------------------------------------------------------------------------

model:
  _target_: sbnd.model.SBNDLitModule
  decoder:  ${decoder}
  optimizer: ${optimizer}
  lr_scheduler: ${lr_scheduler} 
