# @package _global_
#
# Default evaluation preset for the (128,64) polar code from RPTU

snr_min: 1.0
snr_max: 6.5
snr_step: 0.5

batch_size: 8192
num_batches: 8192
num_workers: 12

tts:
  _target_: sbnd.tts.TTADecoder
  num_perms: 8
  transform:
    _partial_: true
    _target_: sbnd.transforms.GenericPerms
    mat_file: ${perms_dir}/perms.polar.128.mat
    num_perms: 1024