# Code-automorphism transforms for SBND.
#
# These classes are used both for:
#   - training-time data augmentation, by passing one as the `transform`
#     argument of `SBNDDataModule` (only with pre-computed datasets — on-demand
#     mode generates fresh samples per step so it does not need augmentation);
#   - test-time augmentation, by passing one as the `transform` argument of
#     `sbnd.tts.TTADecoder`.
#
# Common interface
# ----------------
# Each class exposes:
#   self.perms        : Tensor of shape (n_perms, code.n), int64.
#                       Each row is a valid permutation of [0, ..., code.n - 1]
#                       that is a code automorphism.
#   self.n_perms      : int, number of permutations stored in `self.perms`.
#   __call__(y, e)    : draw one random permutation per sample and apply it to
#                       `y` and `e` jointly. Used by the training-augmentation
#                       path.
#   sample_perms(bs)  : draw `bs` random permutations and return them together
#                       with their inverses. Used by `TTADecoder`. Implemented
#                       once in the `BasePerms` base class.

import torch, numpy as np
import h5py  # type: ignore[import-untyped]
from torch import Tensor
from scipy.io import loadmat  # type: ignore[import-untyped]
from .codes import LinearCode
from .utils import get_rank_zero_logger

log = get_rank_zero_logger(__name__)


class BasePerms:
    """Shared base for permutation classes. Subclasses must populate
    `self.perms` (Tensor of shape (n_perms, code.n)) and `self.n_perms` (int).
    """

    perms: Tensor
    n_perms: int

    def sample_perms(self, bs: int) -> tuple[Tensor, Tensor]:
        """Draw `bs` random permutations and return them together with their
        inverses, both of shape (bs, code.n). Used by `TTADecoder` to permute
        received words and inverse-permute the resulting logits.
        """
        n = self.perms.size(1)
        perms = self.perms[torch.randint(self.n_perms, (bs,))]
        src = torch.arange(n)[None].repeat(bs, 1)
        perms_inv = torch.empty_like(perms)
        perms_inv.scatter_(dim=1, index=perms, src=src)
        return perms, perms_inv


class BCHPerms(BasePerms):
    """Cyclic × Frobenius permutations for BCH codes.

    Builds the subgroup of automorphisms generated by the cyclic shift and the
    Frobenius map (`i → 2·i mod n`), of size `n · log2(n+1)`. For extended BCH
    codes (`is_extended=True`), each permutation is padded with the fixed
    overall-parity bit at the end (this only covers a small subset of the full
    automorphism group of the eBCH code; for the full group, use `GenericPerms`
    with a precomputed `.mat` file).
    """

    def __init__(self, code: LinearCode, is_extended: bool = False) -> None:
        # precompute the subgroup of cyclic x frobenius permutations
        n = code.n - 1 if is_extended else code.n
        idx = torch.arange(
            n, dtype=torch.int64
        )  # take_along_dim requires int64 indices
        b = torch.log2(torch.tensor(n + 1, dtype=torch.int)).int()
        perms = [(j + idx * 2**l) % n for j in range(n) for l in range(b)]
        perms = torch.stack(perms)
        self.n_perms = perms.size(0)
        if is_extended:
            # add the fixed extension bit to the end of each permutation
            perms = torch.hstack(
                [perms, n * torch.ones(self.n_perms, 1, dtype=torch.int64)]
            )
        self.perms = perms
        log.info(
            f"Data augmentation: using the {self.n_perms} cyclic x Frobenius permutations of {code}"
        )
        if is_extended:
            log.info(
                f"Note: This is only a small subset of the full automorphism group of the eBCH code"
            )

    def __call__(self, y: Tensor, e: Tensor) -> tuple[Tensor, Tensor]:
        bs = y.size(0)
        perms = self.perms[torch.randint(self.n_perms, (bs,))]
        yp = y.take_along_dim(perms, dim=-1)
        ep = e.take_along_dim(perms, dim=-1)
        return yp, ep


class QCPerms(BasePerms):
    """Quasi-cyclic shift permutations for QC-LDPC codes.

    Builds the `Zc` permutations corresponding to a cyclic shift by 0, 1, ...,
    Zc-1 within each circulant block of size `Zc`. Requires that `Zc` divides
    `code.n`.
    """

    def __init__(self, code: LinearCode, Zc: int = 1) -> None:
        assert (
            code.n // Zc
        ) * Zc == code.n, "the circulant size Zc must divide the code length"
        # precompute the Zc quasi-cyclic permutations
        perms = [
            Zc * (torch.arange(code.n) // Zc) + (torch.arange(code.n) + i) % Zc
            for i in range(Zc)
        ]
        self.perms = torch.stack(perms)
        self.n_perms = self.perms.size(0)
        log.info(
            f"Data augmentation: using the {self.n_perms} quasi-cyclic permutations of code {code}"
        )

    def __call__(self, y: Tensor, e: Tensor) -> tuple[Tensor, Tensor]:
        bs = y.size(0)
        perms = self.perms[torch.randint(self.n_perms, (bs,))]
        yp = y.take_along_dim(perms, dim=-1)
        ep = e.take_along_dim(perms, dim=-1)
        return yp, ep


class GenericPerms(BasePerms):
    """Load an arbitrary set of code automorphisms from a `.mat` file.

    Useful for codes whose automorphism group is not directly captured by
    `BCHPerms` or `QCPerms` — e.g. Reed-Muller codes (affine group) or polar
    codes (factor-graph automorphisms).

    Expected `.mat` file structure
    ------------------------------
    The file must contain a single field `perms` of shape `(n_perms, code.n)`.
    Each row must be a valid permutation of `[0, 1, ..., code.n - 1]`. Both
    MATLAB v7 and v7.3 (HDF5) formats are supported.

    Two example files are shipped under `data/perms/`:
      - `perms.rm.32.mat`    — 1024 affine-group permutations of length 32,
                               valid for any RM(32, k) code.
      - `perms.polar.128.mat` — 4096 factor-graph permutations of length 128,
                                valid for any polar(128, k) code.

    Arguments
    ---------
    code      : LinearCode whose code length must match the second dim of `perms`.
    mat_file  : path to the .mat file. The `.mat` extension is appended if missing.
    num_perms : optional. If set and smaller than the number of rows in the file,
                only the first `num_perms` rows are kept (lets you study how TTA /
                training-augmentation performance scales with the size of the
                automorphism subset). If unset (default), all rows are loaded.
    """

    def __init__(
        self, code: LinearCode, mat_file: str, num_perms: int | None = None
    ) -> None:
        if not mat_file.endswith(".mat"):
            mat_file += ".mat"
        try:
            # v7 mat files or earlier are supported by scipy.io
            matlab_data = loadmat(mat_file, squeeze_me=True)
        except NotImplementedError:
            # but not v7.3 (=HDF5) mat files, for which we need h5py
            with h5py.File(mat_file, "r") as f:
                if "perms" not in f:
                    raise ValueError(f"Dataset perms not found in {mat_file}")
                # take_along_dim requires int64 indices
                perms = torch.from_numpy(f["perms"][:].astype(np.int64).transpose())
        else:
            if "perms" not in matlab_data:
                raise ValueError(f"Dataset perms not found in {mat_file}")
            # take_along_dim requires int64 indices
            perms = torch.tensor(matlab_data["perms"], dtype=torch.int64)
        assert (
            perms.ndim == 2 and perms.size(1) == code.n
        ), "permutations must be a 2D array of shape (n_perms, code.n)"
        total_perms = perms.size(0)
        if num_perms is not None and num_perms > total_perms:
            log.warning(
                f"Requested {num_perms} permutations but file only contains {total_perms}; using all {total_perms}"
            )
        self.n_perms = total_perms if num_perms is None else min(num_perms, total_perms)
        self.perms = perms[: self.n_perms]
        log.info(
            f"Data augmentation: using {self.n_perms} permutations read from file {mat_file}"
        )

    def __call__(self, y: Tensor, e: Tensor) -> tuple[Tensor, Tensor]:
        bs = y.size(0)
        perms = self.perms[torch.randint(self.n_perms, (bs,))]
        yp = y.take_along_dim(perms, dim=-1)
        ep = e.take_along_dim(perms, dim=-1)
        return yp, ep


if __name__ == "__main__":
    pass
